{% set name = "python-picard" %}
{% set version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dad377c9a50f9850f85841eba0ffb58ad557885ca93364bb73153f33210b52e2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - numpy  # for numpy.distutils.core.setup()
  run:
    - python >=3.6
    - numpy >=1.8
    - matplotlib-base >=1.3
    - numexpr >=2.0
    - scipy >=0.19
    - scikit-learn >=0.23

test:
  imports:
    - picard
    - picard.densities
    - picard.solver

about:
  home: https://pierreablin.github.io/picard/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Preconditioned ICA for Real Data (PICARD) algorithm and its orthogonal version (PICARD-O)
  description: |
    This is a library to run the Preconditioned ICA for Real Data (PICARD)
    algorithm and its orthogonal version (PICARD-O). These algorithms
    show fast convergence even on real data for which sources independence do
    not perfectly hold.
  dev_url: https://github.com/pierreablin/picard

extra:
  recipe-maintainers:
    - hoechenberger
